---
title: "Presentacion Tp Series"
author: "M. Ines Cañizares"
output: html_document
---
```{r load-packages, echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(feasts)
library(tidyverse)
library(ggplot2)
library(fpp3)
library(tsibble)
library(lubridate)
library(forecast)
library(rmarkdown)
library(knitr)
library(gridExtra)
library(forecast)
library(purrr)
library(kableExtra)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align="center")
knitr::opts_chunk$set(out.width="70%")
knitr::opts_chunk$set(out.height="70%")
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(echo=FALSE)
``` 

```{r Carga de datos}

# Cargar los datos
datos <- read.delim("Multiple_Cause_of_Death__1999-2020.xls", sep = "\t")

datos <- datos |>
  mutate(Month = yearmonth(`Month.Code`)) |>
  select(Month, muertes = Deaths) |>
  as_tsibble(index = Month)

datos
```

```{r}
# Filtramos según los años que voy a utilizar (1999-01-01 a 2018-12-31)
datos_filtrado <- datos %>%
  filter_index("1999 Jan" ~ "2018 Dec")

```

```{r, fig.cap='Evolución de las muertes mensuales por ACV en Estados Unidos (1999–2018)'}

# Grafico de la serie
ggplot(data = datos_filtrado, aes(x = Month, y = muertes)) +
  geom_line(color = "violetred3", linewidth = 0.6) +
  labs(
    x = "Fecha",
    y = "Cantidad de muertes"
  ) +
  theme_minimal() +
  scale_x_yearmonth(date_breaks = "12 months", date_labels = "%Y") +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 1))
```

```{r, fig.cap='Distribución Anual de Muertes por ACV en EE.UU. (1999–2018)'}
datos_filtrado %>%
  mutate(año = year(Month)) %>%
  ggplot(aes(x = as.factor(año), y = muertes)) +
  geom_boxplot(fill = "violetred3") +
  labs(
    x = "Año",
    y = "Cantidad de muertes"
  ) +
  theme_minimal()
```

```{r, fig.cap= 'Gráfico estacional de Muertes por ACV en EE.UU. (1999–2018)'}
datos_filtrado %>%
  gg_season(muertes, labels = "both") +
  labs(
    y = "Cantidad de muertes",
    x = "Mes"
  ) +
  theme_minimal() +
  coord_cartesian(clip = "off")   # Evita el recorte de las etiquetas
```

```{r, fig.cap='Gráfico de subseries estacionales de muertes por ACV en EE.UU. (1999-2018)'}
datos_filtrado |>
  gg_subseries(muertes) +
  labs(
    y = "Cantidad de muertes",
    x = "Mes"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),  
    axis.ticks.x = element_blank()
  )
```

```{r, fig.cap='Función de Autocorrelación de las Muertes por ACV'}
datos_filtrado %>%
  ACF(muertes, lag_max = 36) %>%
  autoplot() +
  labs(
    x = "Rezago (meses)",
    y = "Autocorrelación"
  ) +
  theme_minimal(base_size = 13) +
  theme(
    plot.title = element_text(face = "bold"),
    plot.subtitle = element_text(color = "gray30")
  )
```